name: sbi_emi_calculator
description: A web application to calculate and display the EMI (Equated Monthly Installment) loan amortization schedule for SBI credit card loans.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  google_generative_ai: ^0.4.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1
  pdf: ^3.10.8
  printing: ^5.12.0
  excel: ^4.0.3
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  flutter_markdown: ^0.7.1
  url_launcher: ^6.3.0
  file_saver: ^0.2.12 # For web file saving


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sbi_logo.svg
